### PR TITLE
make the project ARR

### PR DESCRIPTION
**Pull request by rlnt**
This pull request switches the licensing of the project to All Rights Reserved. It is important to note that the change will only apply to future versions. This means only version 1.0.0 and higher. Releases for Minecraft 1.20.1 and below are not affected.

All commits, code changes, and contents after this commit are protected. The authors (Almost Reliable) no longer allow use, modification, or distribution without explicit permission. Forking the project is allowed for the purpose of making pull requests back to the upstream repository. Contributions in a pull request will fall under the new license.

Contributors to this project are hereby requested to express their consent to the change of license. If this consent is not given, relevant commits will be reverted. By giving your consent, you agree that your changes to this project will be under the new license. Contributors whose consent is required will be assessed based on the added code. This includes changes to functionality, refactorings, and additional support. Changes such as translations will not be considered.

Required consents:<br>
- [X] @rlnt - one of the two main authors and member of team Almost Reliable
- [x] @LLytho - one of the two main authors and member of team Almost Reliable
- [x] @embeddedt - performance improvements (reference https://github.com/AlmostReliable/almostunified/pull/35)
- [x] @PersiflageTheNinth - support for Ars Nouveau and add-ons (reference https://github.com/AlmostReliable/almostunified/pull/44)
- [x] @pietro-lopes - support for TerraFirmaCraft (reference https://github.com/AlmostReliable/almostunified/pull/69)

Please let us know in the answers whether you agree to the relicensing of the project.

### CODE REVIEW

**Comment by rlnt** [comment]
I, as a contributor to the project, hereby confirm that all my contributions may be used under the new license.

**Comment by LLytho** [comment]
I, as a contributor to the project, hereby confirm that all my contributions may be used under the new license.

**Comment by embeddedt** [comment]
I, as a contributor to the project, hereby confirm that all my contributions may be used under the new license.

**Comment by PersiflageTheNinth** [comment]
I, as a contributor to the project, hereby confirm that all my contributions may be used under the new license.

**Comment by pietro-lopes** [comment]
I, as a contributor to the project, hereby confirm that all my contributions may be used under the new license.

**Pull request merged**
